# Site settings
author: Yamira Basabe
title: Dreamers===Doers
header-img: img/home-bg.png
email: yamirabasabe@gmail.com
copyright_name: Yamira Basabe
description: > # this means to ignore newlines until "baseurl:"
  My SE Bootcamp Path
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: YamiraWiseUp
github_username:  ybasabe

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
